### ISSUE TITLE
Straight edge lines clip through sphere in the spherical graph 

### ISSUE THREAD

**Issue by clintvrazel** [davidpiegza/Graph-Visualization#26]
I noticed edges that looked like they were going nowhere in the spherical graph, but at some zoom levels you can see most or all of them. It appears they are clipping through the spherical surface because they are straight lines and not curved. Do you plan on implementing some great circle arcs? Since the edges don't have any mass it wouldn't affect the simulation too much, but I understand it might be more computationally expensive - although you wouldn't have to mix spherical and euclidean coordinates if you abandoned straight lines in the spherical graph.

**Comment by davidpiegza** [comment]
@clintvrazel Sorry the late reply. This repo is not maintained anymore so there are no plans to add this feature. PRs are welcome, though :)
