### ISSUE TITLE
Apply various weights of force to links

### ISSUE THREAD

**Issue by kino-dome** [davidpiegza/Graph-Visualization#27]
Hi,

Is it possible to apply different weights to the connections? For instance if I have two kinds of edges and I want to dedicate different weight to each kind. I guess I can add multiple connections of the same kind to increase the way, right? Or is there a better way?

Cheers

**Comment by davidpiegza** [comment]
@kino-dome This is not supported out-of-the-box but you could add a `weight` property to the nodes. You would also need to amend the force-directed-layout to include the weight in the calculation.
