### ISSUE TITLE
Source code is out-of-date

### ISSUE THREAD

**Issue by ejstembler** [davidpiegza/Graph-Visualization#6]
It's clear from your demo running on Heroku, that this version of the source code is slightly out-of-date.  Someone could reverse engineer the new SimpleGraph, however it's been compressed/minified into the Application.js file.  It would be better if this repo were updated.

Thanks!

**Comment by davidpiegza** [comment]
The Heroku app has been replaced with a "GitHub pages" site. Closing this.
